# Generated by Django 4.2.4 on 2024-01-14 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='position',
        ),
    ]
