# Generated by Django 4.2.4 on 2024-01-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_remove_experience_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='position',
        ),
        migrations.AddField(
            model_name='experience',
            name='position',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
    ]
