# Generated by Django 4.2.4 on 2024-01-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_remove_education_position_experience_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='endDate',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
