# Generated by Django 4.2.4 on 2024-01-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_education_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='startDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='startDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.DateField(),
        ),
    ]
