# Generated by Django 4.2.4 on 2024-01-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_alter_education_enddate_alter_education_startdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=255)),
                ('scholarurl', models.URLField()),
                ('author', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('articleurl', models.URLField()),
            ],
        ),
    ]
