# Generated by Django 4.2.4 on 2024-01-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=150)),
                ('projectDate', models.DateField()),
                ('projectUrl', models.URLField()),
                ('projectTitle', models.CharField(max_length=255)),
                ('img1', models.ImageField(upload_to='images/')),
                ('img2', models.ImageField(upload_to='images/')),
                ('img3', models.ImageField(upload_to='images/')),
                ('desc', models.TextField()),
            ],
        ),
    ]
