# Generated by Django 4.2.4 on 2024-01-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
